//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MailSimOperations {
    
    private BaseMailOperation[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EventMonitor", typeof(MailSimOperationsEventMonitor))]
    [System.Xml.Serialization.XmlElementAttribute("FolderCreate", typeof(MailSimOperationsFolderCreate))]
    [System.Xml.Serialization.XmlElementAttribute("FolderDelete", typeof(MailSimOperationsFolderDelete))]
    [System.Xml.Serialization.XmlElementAttribute("MailDelete", typeof(MailSimOperationsMailDelete))]
    [System.Xml.Serialization.XmlElementAttribute("MailForward", typeof(MailSimOperationsMailForward))]
    [System.Xml.Serialization.XmlElementAttribute("MailMove", typeof(MailSimOperationsMailMove))]
    [System.Xml.Serialization.XmlElementAttribute("MailReply", typeof(MailSimOperationsMailReply))]
    [System.Xml.Serialization.XmlElementAttribute("MailSend", typeof(MailSimOperationsMailSend))]
    public BaseMailOperation[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsEventMonitor : BaseMailOperation {
    
    private string folderField;
    
    /// <remarks/>
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BaseMailOperation {
    
    private string operationNameField;
    
    private string sleepField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OperationName {
        get {
            return this.operationNameField;
        }
        set {
            this.operationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Sleep {
        get {
            return this.sleepField;
        }
        set {
            this.sleepField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RandomAttachments {
    
    private string countField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RandomRecipients {
    
    private string distributionListField;
    
    private string valueField;
    
    public RandomRecipients() {
        this.distributionListField = "";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string DistributionList {
        get {
            return this.distributionListField;
        }
        set {
            this.distributionListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsFolderCreate : BaseMailOperation {
    
    private string folderPathField;
    
    private string folderNameField;
    
    private string countField;
    
    /// <remarks/>
    public string FolderPath {
        get {
            return this.folderPathField;
        }
        set {
            this.folderPathField = value;
        }
    }
    
    /// <remarks/>
    public string FolderName {
        get {
            return this.folderNameField;
        }
        set {
            this.folderNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsFolderDelete : BaseMailOperation {
    
    private string folderPathField;
    
    private string folderNameField;
    
    private string countField;
    
    /// <remarks/>
    public string FolderPath {
        get {
            return this.folderPathField;
        }
        set {
            this.folderPathField = value;
        }
    }
    
    /// <remarks/>
    public string FolderName {
        get {
            return this.folderNameField;
        }
        set {
            this.folderNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsMailDelete : BaseMailOperation {
    
    private string folderField;
    
    private string subjectField;
    
    private string countField;
    
    private string mailCountForRandomizationField;
    
    private string userCountForRandomizationField;
    
    public MailSimOperationsMailDelete() {
        this.mailCountForRandomizationField = "500";
        this.userCountForRandomizationField = "100";
    }
    
    /// <remarks/>
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    public string Subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("500")]
    public string MailCountForRandomization {
        get {
            return this.mailCountForRandomizationField;
        }
        set {
            this.mailCountForRandomizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("100")]
    public string UserCountForRandomization {
        get {
            return this.userCountForRandomizationField;
        }
        set {
            this.userCountForRandomizationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsMailForward : BaseMailOperation {
    
    private string folderField;
    
    private string[] recipientField;
    
    private RandomRecipients randomRecipientsField;
    
    private string mailSubjectToForwardField;
    
    private string forwardBodyField;
    
    private string[] attachmentField;
    
    private RandomAttachments randomAttachmentsField;
    
    private string countField;
    
    private string mailCountForRandomizationField;
    
    private string userCountForRandomizationField;
    
    public MailSimOperationsMailForward() {
        this.mailCountForRandomizationField = "500";
        this.userCountForRandomizationField = "100";
    }
    
    /// <remarks/>
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Recipient")]
    public string[] Recipient {
        get {
            return this.recipientField;
        }
        set {
            this.recipientField = value;
        }
    }
    
    /// <remarks/>
    public RandomRecipients RandomRecipients {
        get {
            return this.randomRecipientsField;
        }
        set {
            this.randomRecipientsField = value;
        }
    }
    
    /// <remarks/>
    public string MailSubjectToForward {
        get {
            return this.mailSubjectToForwardField;
        }
        set {
            this.mailSubjectToForwardField = value;
        }
    }
    
    /// <remarks/>
    public string ForwardBody {
        get {
            return this.forwardBodyField;
        }
        set {
            this.forwardBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment")]
    public string[] Attachment {
        get {
            return this.attachmentField;
        }
        set {
            this.attachmentField = value;
        }
    }
    
    /// <remarks/>
    public RandomAttachments RandomAttachments {
        get {
            return this.randomAttachmentsField;
        }
        set {
            this.randomAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("500")]
    public string MailCountForRandomization {
        get {
            return this.mailCountForRandomizationField;
        }
        set {
            this.mailCountForRandomizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("100")]
    public string UserCountForRandomization {
        get {
            return this.userCountForRandomizationField;
        }
        set {
            this.userCountForRandomizationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsMailMove : BaseMailOperation {
    
    private string sourceFolderField;
    
    private string destinationFolderField;
    
    private string subjectField;
    
    private string countField;
    
    private string mailCountForRandomizationField;
    
    public MailSimOperationsMailMove() {
        this.mailCountForRandomizationField = "500";
    }
    
    /// <remarks/>
    public string SourceFolder {
        get {
            return this.sourceFolderField;
        }
        set {
            this.sourceFolderField = value;
        }
    }
    
    /// <remarks/>
    public string DestinationFolder {
        get {
            return this.destinationFolderField;
        }
        set {
            this.destinationFolderField = value;
        }
    }
    
    /// <remarks/>
    public string Subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("500")]
    public string MailCountForRandomization {
        get {
            return this.mailCountForRandomizationField;
        }
        set {
            this.mailCountForRandomizationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsMailReply : BaseMailOperation {
    
    private string folderField;
    
    private string mailSubjectToReplyField;
    
    private string replyBodyField;
    
    private string[] attachmentField;
    
    private RandomAttachments randomAttachmentsField;
    
    private bool replyAllField;
    
    private string countField;
    
    private string mailCountForRandomizationField;
    
    private string userCountForRandomizationField;
    
    public MailSimOperationsMailReply() {
        this.mailCountForRandomizationField = "500";
        this.userCountForRandomizationField = "100";
    }
    
    /// <remarks/>
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    public string MailSubjectToReply {
        get {
            return this.mailSubjectToReplyField;
        }
        set {
            this.mailSubjectToReplyField = value;
        }
    }
    
    /// <remarks/>
    public string ReplyBody {
        get {
            return this.replyBodyField;
        }
        set {
            this.replyBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment")]
    public string[] Attachment {
        get {
            return this.attachmentField;
        }
        set {
            this.attachmentField = value;
        }
    }
    
    /// <remarks/>
    public RandomAttachments RandomAttachments {
        get {
            return this.randomAttachmentsField;
        }
        set {
            this.randomAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReplyAll {
        get {
            return this.replyAllField;
        }
        set {
            this.replyAllField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("500")]
    public string MailCountForRandomization {
        get {
            return this.mailCountForRandomizationField;
        }
        set {
            this.mailCountForRandomizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("100")]
    public string UserCountForRandomization {
        get {
            return this.userCountForRandomizationField;
        }
        set {
            this.userCountForRandomizationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MailSimOperationsMailSend : BaseMailOperation {
    
    private string[] recipientField;
    
    private RandomRecipients randomRecipientsField;
    
    private string subjectField;
    
    private string bodyField;
    
    private string[] attachmentField;
    
    private RandomAttachments randomAttachmentsField;
    
    private string countField;
    
    private string userCountForRandomizationField;
    
    public MailSimOperationsMailSend() {
        this.userCountForRandomizationField = "100";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Recipient")]
    public string[] Recipient {
        get {
            return this.recipientField;
        }
        set {
            this.recipientField = value;
        }
    }
    
    /// <remarks/>
    public RandomRecipients RandomRecipients {
        get {
            return this.randomRecipientsField;
        }
        set {
            this.randomRecipientsField = value;
        }
    }
    
    /// <remarks/>
    public string Subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    public string Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attachment")]
    public string[] Attachment {
        get {
            return this.attachmentField;
        }
        set {
            this.attachmentField = value;
        }
    }
    
    /// <remarks/>
    public RandomAttachments RandomAttachments {
        get {
            return this.randomAttachmentsField;
        }
        set {
            this.randomAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("100")]
    public string UserCountForRandomization {
        get {
            return this.userCountForRandomizationField;
        }
        set {
            this.userCountForRandomizationField = value;
        }
    }
}
