//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MailSimOptions {
    
    private MailSimOptionsProviderType providerTypeField;
    
    private string userNameField;
    
    private string passwordField;
    
    private bool disableOutlookPromptsField;
    
    private bool disableOutlookPromptsFieldSpecified;
    
    /// <remarks/>
    public MailSimOptionsProviderType ProviderType {
        get {
            return this.providerTypeField;
        }
        set {
            this.providerTypeField = value;
        }
    }
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public bool DisableOutlookPrompts {
        get {
            return this.disableOutlookPromptsField;
        }
        set {
            this.disableOutlookPromptsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DisableOutlookPromptsSpecified {
        get {
            return this.disableOutlookPromptsFieldSpecified;
        }
        set {
            this.disableOutlookPromptsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum MailSimOptionsProviderType {
    
    /// <remarks/>
    OOM,
    
    /// <remarks/>
    HTTP,
    
    /// <remarks/>
    SDK,
}
