//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace MailSim {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MailSimSequence {
        
        private MailSimSequenceOperationGroup[] operationGroupField;
        
        private string logFileLocationField;
        
        private bool disableOutlookPromptField;
        
        private bool disableOutlookPromptFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperationGroup")]
        public MailSimSequenceOperationGroup[] OperationGroup {
            get {
                return this.operationGroupField;
            }
            set {
                this.operationGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LogFileLocation {
            get {
                return this.logFileLocationField;
            }
            set {
                this.logFileLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DisableOutlookPrompt {
            get {
                return this.disableOutlookPromptField;
            }
            set {
                this.disableOutlookPromptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisableOutlookPromptSpecified {
            get {
                return this.disableOutlookPromptFieldSpecified;
            }
            set {
                this.disableOutlookPromptFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MailSimSequenceOperationGroup {
        
        private MailSimSequenceOperationGroupTask[] taskField;
        
        private string nameField;
        
        private string operationFileField;
        
        private string iterationsField;
        
        private string sleepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public MailSimSequenceOperationGroupTask[] Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperationFile {
            get {
                return this.operationFileField;
            }
            set {
                this.operationFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Iterations {
            get {
                return this.iterationsField;
            }
            set {
                this.iterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Sleep {
            get {
                return this.sleepField;
            }
            set {
                this.sleepField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MailSimSequenceOperationGroupTask {
        
        private string nameField;
        
        private string iterationsField;
        
        private string sleepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Iterations {
            get {
                return this.iterationsField;
            }
            set {
                this.iterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Sleep {
            get {
                return this.sleepField;
            }
            set {
                this.sleepField = value;
            }
        }
    }
}
